"""Pydantic schemas for LLM inputs and outputs."""
from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional


class AnalystOutput(BaseModel):
    """Structured output from the LLM Analyst."""

    generated_at: datetime
    direction: str = Field(description="bullish | bearish | neutral")
    confidence: float = Field(description="0.0 to 1.0", ge=0.0, le=1.0)
    primary_drivers: list[str] = Field(default_factory=list)
    counter_drivers: list[str] = Field(default_factory=list)
    narrative: str = Field(description="Narrative explanation of market state")
    key_events: list[str] = Field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at.isoformat(),
            "direction": self.direction,
            "confidence": self.confidence,
            "primary_drivers": self.primary_drivers,
            "counter_drivers": self.counter_drivers,
            "narrative": self.narrative,
            "key_events": self.key_events,
        }


class TradePlan(BaseModel):
    """Final trading guidance plan generated by the Planner."""

    generated_at: datetime
    snapshot_id: int

    stance: str = Field(description="long | short | neutral")
    horizon_hours: int
    confidence: float = Field(ge=0.0, le=1.0)

    entry_rule: str = Field(description="Condition for entry")
    stop_rule: str = Field(description="Stop-loss condition")
    take_profit_rule: str = Field(description="Take-profit condition")
    invalidation_rule: str = Field(description="What invalidates this plan")
    risk_note: str = Field(description="Risk caveats")

    why: str = Field(description="Rationale summary")

    model_version: str
    prompt_version: str
    strategy_version: str

    expected_return_pct: float = 0.0

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at.isoformat(),
            "snapshot_id": self.snapshot_id,
            "stance": self.stance,
            "horizon_hours": self.horizon_hours,
            "confidence": self.confidence,
            "entry_rule": self.entry_rule,
            "stop_rule": self.stop_rule,
            "take_profit_rule": self.take_profit_rule,
            "invalidation_rule": self.invalidation_rule,
            "risk_note": self.risk_note,
            "why": self.why,
            "model_version": self.model_version,
            "prompt_version": self.prompt_version,
            "strategy_version": self.strategy_version,
            "expected_return_pct": self.expected_return_pct,
        }


class LLMResponse(BaseModel):
    """Raw response from any LLM provider."""

    raw_text: str
    parsed: dict
    model_used: str
    tokens_used: Optional[int] = None
